# MASTER CONFIG
bind 0.0.0.0
port 6379

# SASL/ACL Security (reusing our existing file)
aclfile /usr/local/etc/redis/users.acl

# Persistence
appendonly yes

# REPLICATION SECURITY
# Master needs a password for replicas to connect to it
masterauth admin_pass
