# REDIS CONFIGURATION
# Load the ACL file from the current directory (or absolute path)
aclfile ./users.acl

# Network
bind 127.0.0.1
port 6379

# Persistence
appendonly yes

# Memory
maxmemory 256mb
maxmemory-policy allkeys-lru
