# REPLICA CONFIG
bind 0.0.0.0
port 6379

aclfile /usr/local/etc/redis/users.acl

# Who is the master? (Docker service name)
replicaof redis-master 6379

# Authentication
masterauth admin_pass
masteruser admin
